name: ML_AutoTrained_Using_Drift_Detection


on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest 

        steps:
            #STEP 1
            - name: Checkout repository
              uses: actions/checkout@v3 

            #STEP 2
            - name: Set up Python
              uses: actions/setup-python@v4
              with: 
                python-version: '3.13'

            #STEP 3
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r end_to_end_ml_project/requirements.txt
            #STEP 4
            - name: Run drift_retraining_dag.py
              run: |
                python end_to_end_ml_project/dags/drift_retraining_dag.py
              
